[package]
name = "securefs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bcrypt = "0.13.0"
getrandom = "0.2.8"
zeroize = "1.5.7"
aes = "0.8.2"